export const magicDeck = [
  ["Erode", 4],
  ["Surrak, Elusive Hunter", 1],
  ["Lumbering Worldwagon", 2],
  ["Bushwhack", 2],
  ["Earthbender Ascension", 4],
  ["Temple Garden", 2],
  ["Forest", 7],
  ["Sazh's Chocobo", 4],
  ["Icetill Explorer", 2],
  ["Keen-Eyed Curator", 1],
  ["Llanowar Elves", 4],
  ["Badgermole Cub", 4],
  ["Fabled Passage", 4],
  ["Dyadrine, Synthesis Amalgam", 2],
  ["Hushwood Verge", 4],
  ["Mightform Harmonizer", 4],
  ["Escape Tunnel", 3],
  ["Plains", 2],
  ["Ba Sing Se", 3],
  ["Mossborn Hydra", 1],
];

export const yugiohDeck = [
  ["Ghost Ogre & Snow Rabbit", 2],
  ["Sky Striker Ace - Roze", 2],
  ["Ghost Belle & Haunted Mansion", 1],
  ["Droll & Lock Bird", 2],
  ["Sky Striker Ace - Raye", 3],
  ["Ash Blossom & Joyous Spring", 3],
  ["Sky Striker Special Maneuver - Lemnisgate!", 2],
  ["Forbidden Crown", 2],
  ["Pot of Desires", 3],
  ["Triple Tactics Talent", 1],
  ["Sky Striker Mobilize - Linkage!", 3],
  ["The Fallen & The Virtuous", 3],
  ["Mystical Space Typhoon", 1],
  ["Sky Striker Mecha - Widow Anchor", 3],
  ["Reinforcement of the Army", 1],
  ["Sky Striker Mecha - Shark Cannon", 1],
  ["Sky Striker Mobilize - Engage!", 3],
  ["Radiant Typhoon Vision", 3],
  ["Called by the Grave", 1],
];

export const tournamentSources = {
  magic: {
    archetype: "Selesnya Landfall",
    event: "Pro Tour Secrets of Strixhaven",
    eventDate: "2026-05-03",
    pilot: "Nathan Steuer",
    sourceUrl: "https://magic.gg/news/pro-tour-secrets-of-strixhaven-top-8-players-and-decks",
  },
  yugioh: {
    archetype: "Sky Striker",
    event: "North America WCQ 2026",
    eventDate: "2026-07-11",
    pilot: "Ryan Yu",
    sourceUrl: "https://ygoprodeck.com/deck/sky-striker-721413",
  },
};
